### ISSUE TITLE
xpos and ypos for Lu and Lr look wrong

### ISSUE THREAD

**Issue by moose56** [Bowserinator/Periodic-Table-JSON#51]
Comparing the values of xpos and ypos with their neighbours they look to be wrong. Will raise a pull request to better illustrate my point.

Thanks.

**Comment by Bowserinator** [comment]
The position of those two elements depend on how you classify them (I believe in this JSON there's a gap where you highlighted it in the image), if you treat, ie Lawrencium as group 3 it would fill in the gap, but if you keep all the actinides on the same row then Lawrencium would be on the bottom (you can see it if you google images of "periodic table", the placement will vary).

I don't really wanna change it for now since it could break existing projects, but thanks for noticing :)
